### ISSUE TITLE
Размер — это главное!

### ISSUE THREAD

**Issue by MJaroslav** [mts2200/mts2200.github.io#2]
У тебя немного не влазит текст (и скроллов нет), еще репитит фон:

![2024-01-10_03-42](https://github.com/mts2200/mts2200.github.io/assets/16194914/e6ed1681-c0ea-46aa-a40c-0623787a8f3d)

**Comment by mts2200** [comment]
Да я с вебом вообще не дружу. Страницу на коленке за час сделал. Там и на телефонах всё плохо, да и картинку эту заменить нужно, разрешение огромное, грузит долго. Руки вот не доходят

**Comment by MJaroslav** [comment]
>Не дружу

Как доведу свой визиткобилдер до ума, можешь через него сделать сайт, погляди в таком же [репозитории](/MJaroslav/MJaroslav.github.io) моем, там же [сайт](https://mjaroslav.github.io) для примера.
